export const CommentTypes = {
    EDIT_COMMENT_START: 'EDIT_COMMENT_START',
    EDIT_COMMENT_SUCCESS: 'EDIT_COMMENT_SUCCESS',

    DELETE_COMMENT_START: 'DELETE_COMMENT_START',
    DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',

    EDIT_REPLY_COMMENT_START: 'EDIT_REPLY_COMMENT_START',
    EDIT_REPLY_COMMENT_SUCCESS: 'EDIT_REPLY_COMMENT_SUCCESS',

    DELETE_REPLY_COMMENT_START: 'DELETE_REPLY_COMMENT_START',
    DELETE_REPLY_COMMENT_SUCCESS: 'DELETE_REPLY_COMMENT_SUCCESS',

    FETCH_FAILURE: 'FETCH_FAILURE'
}