const HouseTypes = {
    FETCH_ALL_HOUSE_START: 'FETCH_ALL_HOUSE_START',
    FETCH_ALL_HOUSE_SUCCESS: 'FETCH_ALL_HOUSE_SUCCESS',

    GET_HOUSE_BY_ID_START: 'GET_HOUSE_BY_ID_START',
    GET_HOUSE_BY_ID_SUCCESS: 'GET_HOUSE_BY_ID_SUCCESS',

    SEND_COMMENT_START: 'SEND_COMMENT_START',
    SEND_COMMENT_SUCCESS: 'SEND_COMMENT_SUCCESS',

    SEND_REPLY_COMMENT_START: 'SEND_REPLY_COMMENT_START',
    SEND_REPLY_COMMENT_SUCCESS: 'SEND_REPLY_COMMENT_SUCCESS',

    GET_COMMENTS_BY_HOUSE_ID_START: 'GET_COMMENT_BY_HOUSE_ID_START',
    GET_COMMENTS_BY_HOUSE_ID_SUCCESS: 'GET_COMMENT_BY_HOUSE_ID_SUCCESS',

    GET_REPLIES_BY_COMMENT_ID_START: 'GET_REPLIES_BY_COMMENT_ID_START',
    GET_REPLIES_BY_COMMENT_ID_SUCCESS: 'GET_REPLIES_BY_COMMENT_ID_SUCCESS',

    LIKE_COMMENT_START: 'LIKE_COMMENT_START',
    LIKE_COMMENT_SUCCESS: 'LIKE_COMMENT_SUCCESS',

    LIKE_HOUSE_START: 'LIKE_HOUSE_START',
    LIKE_HOUSE_SUCCESS: 'LIKE_HOUSE_SUCCESS',

    SET_HOUSE_LIKES_FROM_AUTH: 'SET_HOUSE_LIKES_FROM_AUTH',
    SET_HOUSE_COMMENTS_FROM_AUTH: 'SET_HOUSE_COMMENTS_FROM_AUTH',

    FETCH_FAILURE: 'FETCH_FAILURE'
}

export default HouseTypes;