const HouseTypes = {
    FETCH_ALL_HOUSE_START: 'FETCH_ALL_HOUSE_START',
    FETCH_ALL_HOUSE_SUCCESS: 'FETCH_ALL_HOUSE_SUCCESS',

    GET_HOUSE_BY_ID_START: 'GET_HOUSE_BY_ID_START',
    GET_HOUSE_BY_ID_SUCCESS: 'GET_HOUSE_BY_ID_SUCCESS',

    SEND_COMMENT_START: 'SEND_COMMENT_START',
    SEND_COMMENT_SUCCESS: 'SEND_COMMENT_SUCCESS',

    GET_COMMENTS_BY_HOUSE_ID_START: 'GET_COMMENT_BY_HOUSE_ID_START',
    GET_COMMENTS_BY_HOUSE_ID_SUCCESS: 'GET_COMMENT_BY_HOUSE_ID_SUCCESS',

    LIKE_COMMENT_START: 'LIKE_COMMENT_START',
    LIKE_COMMENT_SUCCESS: 'LIKE_COMMENT_SUCCESS',
    
    FETCH_FAILURE: 'FETCH_FAILURE'
}

export default HouseTypes;