const AuthTypes = {

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    LOGIN_START: 'LOGIN_START',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
}

export default AuthTypes;