const AuthTypes = {

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    LOGIN_START: 'LOGIN_START',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

    SET_LOGIN_MODE: 'SET_LOGIN_MODE',
    SET_SIGNUP_MODE: 'SET_SIGNUP_MODE',

    SET_PASSWORD_LEVEL: 'SET_PASSWORD_LEVEL',
    CHECK_PASSWORD_START: 'CHECK_PASSWORD_START',
    CHECK_PASSWORD_SUCCESS: 'CHECK_PASSWORD_SUCCESS',
    CHECK_PASSWORD_FAILURE: 'CHECK_PASSWORD_FAILURE',

    SET_ERROR_CONFIRM_PASSWORD: 'SET_ERROR_CONFIRM_PASSWORD'
}

export default AuthTypes;