const ProductTypes = {
    ADD_PRODUCT_START: 'ADD_PRODUCT_START',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',

    ADD_PRODUCT_IMAGE: 'ADD_PRODUCT_IMAGE',

    FETCH_PRODUCTS_START: 'FETCH_PRODUCT_START',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',

    EDIT_PRODUCT_START: 'EDIT_PRODUCT_START',
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',

    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',

    SET_SEARCH_BY_NAME: 'SET_SEARCH_BY_NAME',
    SET_SEARCH_BY_LOCATION: 'SET_SEARCH_BY_LOCATION',

    SEARCH_PRODUCT_BY_NAME_START: 'SEARCH_PRODUCT_BY_NAME_START',
    SEARCH_PRODUCT_BY_NAME_SUCCESS: 'SEARCH_PRODUCT_BY_NAME_SUCCESS',

    SEARCH_PRODUCT_BY_LOCATION_START: 'SEARCH_PRODUCT_BY_LOCATION_START',
    SEARCH_PRODUCT_BY_LOCATION_SUCCESS: 'SEARCH_PRODUCT_BY_LOCATION_SUCCESS',

    FETCH_FAILURE: 'FETCH_FAILURE',

    GET_PRODUCTS_FROM_AUTH: 'GET_PRODUCTS_FROM_AUTH'

    

};

export default ProductTypes;