const ProductTypes = {
    ADD_PRODUCT_START: 'ADD_PRODUCT_START',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',

    ADD_PRODUCT_IMAGE: 'ADD_PRODUCT_IMAGE',

    FETCH_PRODUCTS_START: 'FETCH_PRODUCT_START',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',

    EDIT_PRODUCT_START: 'EDIT_PRODUCT_START',
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',

    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',

    FETCH_FAILURE: 'FETCH_FAILURE',

    

};

export default ProductTypes;